CRVS.UI/Controllers/JobController.cs
using CRVS.Core.IRepositories;
using CRVS.Core.Models;

using Microsoft.AspNetCore.Mvc;


namespace CRVS.UI.Controllers
{
    public class JobController : Controller
    {
        public IBaseRepository<Job> repository;
        public JobController(IBaseRepository<Job> _repository)
        {

            repository = _repository;
        }
        public IActionResult Index()
        {
            
            return View(repository.GetAll());

        }
        public IActionResult Create()

        {


            return View();

        }
        [HttpPost]
        public IActionResult Create(Job job)

        {
           
                repository.Add(job);
           
                return RedirectToAction(nameof(Index));
           
        }
    }
}

CRVS.UI/Views/Job/Create.cshtml
@model Job
@{
    ViewData["Title"] = "Create";
}

<h1>Create New job</h1>

<form method="post" asp-action="Create" asp-controller="Job">
    <table class=" table table-bordered table-striped">

        <tr>
            <td> <label asp-for="JobName"></label> </td>
            <td>
                <input asp-for="JobName" class="form-control" placeholder="Enter Name" />
              
            </td>

        </tr>
       
        <td colspan="2">
            <input type="submit" value="Create" class="btn btn-success" />
            <a asp-action="Index" class="btn btn-warning">Cancel</a>
        </td>

      
    </table>
</form>

CRVS.UI/Views/Job/Index.cshtml
@model IEnumerable<Job>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>



<div>
   
    <a asp-action="Create" asp-asp-controller="Job" class="btn btn-primary">Create new Job</a>
   
</div>


        <table class="table table-bordered table-hover">

            

            <tr>

                <th>@Html.DisplayNameFor(c=>c.JobId)</th>
                <th>@Html.DisplayNameFor(c=>c.JobName)</th>
              


            </tr>
            @foreach (var custeomr in Model)
            {
                <tr>
                    <td>@custeomr.JobId</td>
                     <td>  @custeomr.JobName</td>
                  
                 
                </tr>
            }

        </table>



  