CRVS.UI/Controllers/FacilityTypesController.cs
using CRVS.Core.IRepositories;
using CRVS.Core.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace CRVS.UI.Controllers
{
    public class FacilityTypesController : Controller
    {
        public IBaseRepository<FacilityType> repository;
        public FacilityTypesController(IBaseRepository<FacilityType> _repository)
        {

            repository = _repository;
        }
        public IActionResult Index()
        {

            return View(repository.GetAll());

        }
        /// <summary>
        /// /////////////////create governorate
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()

        {


            return View();

        }
        [HttpPost]
        public IActionResult Create(FacilityType facilityType)

        {

            repository.Add(facilityType);

            return RedirectToAction(nameof(Index));

        }


        [HttpGet]
        public IActionResult Edit(int id)

        {



            if (id == null)
            {

                return RedirectToAction("Index");

            }
            var custom = repository.GetById(id);

            if (custom == null)
            {
                return RedirectToAction("NotFoundCustomer");
            }

            return View(custom);

        }


        [HttpPost]
        public IActionResult Edit(int id, FacilityType facilityType)

        {
        //var data=    repository.GetById(id);
        //    data.GovernorateName = governorate.GovernorateName;
        repository.Update(id, facilityType);
            //repository.SaveChanges();
          


            return RedirectToAction(nameof(Index));
        }




        [HttpGet]
        public IActionResult Delete(int id)
        {
            if (id == null || repository.GetById(id) == null)
            {
                return RedirectToAction(nameof(Index));
            }

           

            return View(repository.GetById(id));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            repository.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Details(int id)
        {
            if (id == null || repository.GetById(id) == null)
            {
                return RedirectToAction(nameof(Index));
            }



            return View(repository.GetById(id));
        }
    }


}





    
    

CRVS.UI/Views/FacilityTypes/Create.cshtml
@model FacilityType

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>FacilityType</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="FacilityTypeName" class="control-label"></label>
                <input asp-for="FacilityTypeName" class="form-control" />
                <span asp-validation-for="FacilityTypeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

CRVS.UI/Views/FacilityTypes/Delete.cshtml
@model FacilityType

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FacilityType</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FacilityTypeName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FacilityTypeName)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="FacilityTypeId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CRVS.UI/Views/FacilityTypes/Details.cshtml
@model FacilityType

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>FacilityType</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FacilityTypeName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FacilityTypeName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="FacilityTypeId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CRVS.UI/Views/FacilityTypes/Edit.cshtml
@model FacilityType

@{
    ViewData["Title"] = "EditGovernorate";
}

<h1>Modify Information of FacilityType</h1>
<h2 class="text-danger">@ViewBag.check</h2>
<form method="post" asp-action="Edit" asp-controller="FacilityTypes">
    <input type="hidden" asp-for="FacilityTypeId" />
    <table class=" table table-bordered table-striped">
        <input type="hidden" asp-for="FacilityTypeId" />
        <tr>
            <td> <label asp-for="FacilityTypeName"></label> </td>
            <td>
                <input asp-for="FacilityTypeName" class="form-control" placeholder="Enter Name" />
                <span class="text-danger" asp-validation-for="FacilityTypeName"></span>
            </td>

        </tr>
       
        <td colspan="2">
            <input type="submit" value="UpDate" class="btn btn-success" />
            <a asp-action="Index" class="btn btn-warning">Cancle</a>
        </td>

        </tr>
    </table>
</form>

CRVS.UI/Views/FacilityTypes/Index.cshtml
@model IEnumerable<FacilityType>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>



<div>

    <a asp-action="Create" asp-asp-controller="Governorates" class="btn btn-primary">Create new Governorate</a>

</div>


<table class="table table-bordered table-hover">



    <tr>

     
        <th>@Html.DisplayNameFor(c=>c.FacilityTypeName)</th>



    </tr>
    @foreach (var item in Model)
    {
        <tr>

            <td>  @item.FacilityTypeName</td>


        </tr>
        <tr>
         <td>
                <a asp-route-id="@item.FacilityTypeId" class="btn btn-warning btn-sm" asp-action="Edit">Edit</a>
                <a asp-route-id="@item.FacilityTypeId" class="btn btn-danger btn-sm" asp-action="Delete">Delete</a>
                <a asp-route-id="@item.FacilityTypeId" class="btn btn-secondary btn-sm" asp-action="Details">Details</a>

                    </td>
                </tr>
    }

</table>